import fs from "fs/promises";
import path from "path";
import { searchClaims, type SearchClaimsOptions } from "../../openbrain/search.js";
import { getClaimWithProvenance } from "../../openbrain/claims.js";
import { getSource } from "../../openbrain/sources.js";
import { getContradictionPairs } from "../../openbrain/relations.js";
import { listTags } from "../../openbrain/tags.js";
import { listRecentCompilationRuns } from "../../openbrain/compilationRuns.js";
import { getOrientationMap } from "../../openbrain/orientation.js";
import { env } from "../../db/env.js";

export type ToolHandler = (args: Record<string, unknown>) => Promise<unknown>;

export const READER_HANDLERS: Record<string, ToolHandler> = {
  async searchClaims(args) {
    const query = String(args["query"] ?? "");
    const topK = typeof args["topK"] === "number" ? (args["topK"] as number) : undefined;
    const filter = (args["filter"] as SearchClaimsOptions["filter"]) ?? undefined;
    const opts: SearchClaimsOptions = {};
    if (topK !== undefined) opts.topK = topK;
    if (filter !== undefined) opts.filter = filter;
    return searchClaims(query, opts);
  },

  async getClaim(args) {
    const id = String(args["id"] ?? "");
    return getClaimWithProvenance(id);
  },

  async getSource(args) {
    const id = String(args["id"] ?? "");
    const source = await getSource(id);
    if (!source) return { found: false, id };
    return { found: true, source };
  },

  async getConcept(args) {
    const slug = String(args["slug"] ?? "");
    if (!/^[a-z0-9][a-z0-9-]*$/.test(slug)) {
      return {
        found: false,
        slug,
        message: `Invalid slug '${slug}'. Slugs are lowercase, hyphenated, and start with a letter or digit.`
      };
    }
    const conceptsDir = path.resolve(env.vaultPath, "concepts");
    const file = path.resolve(conceptsDir, `${slug}.md`);
    if (!file.startsWith(conceptsDir + path.sep) && file !== conceptsDir) {
      return {
        found: false,
        slug,
        message: `Invalid slug '${slug}': resolves outside the concepts directory.`
      };
    }
    try {
      const content = await fs.readFile(file, "utf-8");
      return { found: true, slug, content };
    } catch (err) {
      const isMissing =
        (err as NodeJS.ErrnoException).code === "ENOENT";
      if (isMissing) {
        return {
          found: false,
          slug,
          message:
            `No vault page for slug '${slug}'. The page is generated by compilation; ` +
            `run 'triggerCompilation' if claims exist for this tag.`
        };
      }
      throw err;
    }
  },

  async getContradictions() {
    return getContradictionPairs();
  },

  async listTags() {
    const tags = await listTags();
    const orientation = await getOrientationMap();
    const counts = new Map(orientation.tags.map((t) => [t.slug, t.claimCount]));
    return tags.map((t) => ({
      id: t.id,
      slug: t.slug,
      display: t.display,
      description: t.description,
      claimCount: counts.get(t.slug) ?? 0
    }));
  },

  async getRecentLog(args) {
    const limit = typeof args["limit"] === "number" ? (args["limit"] as number) : 10;
    return listRecentCompilationRuns(limit);
  }
};
